# -*- coding: utf-8 -*-
"""Bayesian_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odp9XCtSoMxLcuB51EzvrZqLq58hl35Z
"""

import numpy as np
import matplotlib.pyplot as plt

#Plotting for Bayesian model

# Produces the plot with the sample output of the deep network for the sound speed, mean values, std's, and real values
def produce_sample_plot(sample):
    # sample: an array with a sample/realisation of pairs of (mass, c_s)
    # Returns: A scatter plot with the sample and mean/std. values.
    stats_x = []
    stats_cs = []
    data_sigma = []
    for j in range(0,7): # range of masses/c_s values
        mean_x, std_x = produce_stats(sample[:,j][:,0]) #np.mean(sample[:,j][:,0]), np.std(sample[:,j][:,0])
        mean_cs, std_cs  = produce_stats(sample[:,j][:,1]) #np.mean(sample[:,j][:,1]), np.std(sample[:,j][:,1])
        stats_x.append([mean_x, std_x])
        stats_cs.append([mean_cs, std_cs])
    stats_x = np.array(stats_x)
    stats_cs = np.array(stats_cs)
    for i in range(len(sample)):
        plt_i = plt.scatter(sample[i][:,0], sample[i][:,1], alpha=i/len(sample))
    plt.errorbar(stats_x[:,0], stats_cs[:,0], xerr = 2*stats_x[:,1], yerr = 2*stats_cs[:,1], fmt ='o', color = 'black')
    plt.xlabel("Mass (normalised)")
    plt.ylabel("Sound speed")
    #plt_i = plt.scatter(stats_x[:,0], stats_cs[:,1],color = 'black')

def plot_pred_vs_real(real_mass, real_cs, predicted_data):
    # predicted_data are the output of ''produce_binning_cs()''. Must be an array.
    # real_mass sets the x-grid. Must be an array
    # real_cs sets the ''real'' c_s. Must be an array
    x = np.linspace(0, 1, 50)
    c_s_interp = np.interp(x, predicted_data[:,0], predicted_data[:,1])
    sigma_interp = np.interp(x, predicted_data[:,0], predicted_data[:,2])
    plt.errorbar(x,c_s_interp, sigma_interp, color = 'black')
    #plt.scatter(real_mass, real_cs, color = 'orange')