# -*- coding: utf-8 -*-
"""Feature_importance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSpwrtBtzy23XWpM-5RObVEwtAm5SKNX
"""

import numpy as np
import pandas as pd

#Permutation importance algorithm

def permutation_importance(model, X_test, y_test, n_iters, random_state=42):
    """
    This function computes the feature importance of our model features M, R and k2.
    This is done specifically by applying a permutation importance algorithm,
    where we randomly permute the columns of our dataset across samples. When
    this happens, we track the change in loss. When the loss is high for a
    feature, we can state it to be of high importance.

    Parameters
        model: keras.Model
              Regression model used for determining speed of sound.
        X_test: list
              Feature list test set.
        y_test: list
              Target list test set.
        n_iters: int
              Amount of times we perform permutation importance algorithm.
        random_state: int
              Random seed used for generating our permutations.

    Returns
        importances: dict
              Dictionary containing feature name, baseline loss, mean permuted loss
              and importance.

    """
    rng = np.random.default_rng(random_state)
    baseline_loss = model.evaluate(X_test, y_test, verbose=0)

    features = {
        "M":  np.arange(0, 30),
        "R":  np.arange(30, 60),
        "k2": np.arange(60, 90)
    }

    importances = []
    for name, cols in features.items():
        losses = []

        for i in range(n_iters):
            #permutation algorithm
            X_permute = X_test.copy()
            permutation_index = rng.permutation(len(X_permute))
            X_permute[:, cols] = X_permute[permutation_index][:, cols]

            loss = model.evaluate(X_permute, y_test, verbose=0)
            losses.append(loss)

        importances.append({
            "feature": name,
            "baseline_loss": baseline_loss,
            "mean_permuted_loss": np.mean(losses),
            "importance": np.mean(losses) - baseline_loss
        })
    importances = pd.DataFrame(importances)

    return importances