# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TDtHgLl8I9JEGgIAzZI7W41ynfgsOVy
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import tensorflow_probability as tfp
tfd = tfp.distributions
tfpl = tfp.layers
import tf_keras

#Deterministic model

##########################
def renormalize(x, k2min, k2max):
    return (x + abs(k2min))/(k2max + abs(k2min))

##########################
def produce_model_class(n_nodes, nodes1, nodes2, nodes3, activation_hidden, ke_init, activation_out,
                              ke_init_out, n_features):
    model = Sequential()
    model.add(Dense(nodes1, activation = activation_hidden, kernel_initializer = ke_init,
                    input_shape = (n_features,)))
    if n_nodes>=2:
        model.add(Dense(nodes2, activation = activation_hidden, kernel_initializer = ke_init))
        if n_nodes>=3:
            model.add(Dense(nodes3, activation = activation_hidden, kernel_initializer = ke_init))

    model.add(Dense(2, activation = activation_out, kernel_initializer = ke_init_out))

    return model

##########################
def produce_model_reg(nodes, activation_hidden, ke_init, activation_out,
                              ke_init_out, n_features):
    model = Sequential()
    model.add(Dense(nodes, activation = activation_hidden, kernel_initializer = ke_init,
                    input_shape = (n_features,)))
    model.add(Dense(15, activation = activation_out, kernel_initializer = ke_init_out))
    return model

##########################
def store_values_class(loss_list, val_loss_list, acc_list, val_acc_list, history):

    loss_list.append(history.history['loss'][-1])
    val_loss_list.append(history.history['val_loss'][-1])
    acc_list.append(history.history['binary_accuracy'][-1])
    val_acc_list.append(history.history['val_binary_accuracy'][-1])

##########################
def store_values_reg(loss_list, val_loss_list, history):

    loss_list.append(history.history['loss'][-1])
    val_loss_list.append(history.history['val_loss'][-1])

##########################
def save_EOS(j, y_test, yeos_test, y_hat, yeos_hat, rep_test, points, save = True):
    list_to_save = y_test[j,:] #save into list EOS parameters (Λ,ρ,cs)
    list_to_save = np.insert(list_to_save, 0, yeos_test[j], axis=0) #add AP4/SLy class
    for i in range(0,rep_test):
        list_hat = y_hat[j+i,:]
        list_hat = np.insert(list_hat, 0, yeos_hat[j+i], axis=0)

        list_to_save = np.vstack((list_to_save, list_hat))
    if save == True:
        np.savetxt(f'EOSj{j}N{points}n{rep_test}.txt', list_to_save)

#Bayesian model

##########################
# This function defines the prior function for the probabilistic deep network.
# The "kernel_size" controls the number of parameters.
# The prior distribution has no trainable variables, and has a zero covariance.
def get_prior(kernel_size, bias_size, dtype=None):
    n = kernel_size + bias_size
    prior_model = tf_keras.Sequential([
       # tfpl.DistributionLambda(lambda t:
       # tfp.distributions.Uniform(low=0.0, high=1, validate_args=False, allow_nan_stats=True, name='Uniform'))

        tfpl.DistributionLambda(lambda t: tfd.MultivariateNormalDiag( loc=tf.zeros(n),scale_diag=tf.ones(n)))
    ])
    return prior_model

##########################
# This function defines the posterior function for the probabilistic deep network,
# assuming it is of Gaussian functional form.
# Covariance of the Gaussian is not zero, and is trainable.
def get_posterior(kernel_size, bias_size, dtype=None):
    n = kernel_size + bias_size
    posterior_model = tf_keras.Sequential([
        tfpl.VariableLayer(tfpl.MultivariateNormalTriL.params_size(n), dtype=dtype),
        tfpl.MultivariateNormalTriL(n)
    ])
    return posterior_model

##########################
# This function produces a statistical sample from the deep network
def produce_sample_cs(X_test, model_def, n_samples = 50, check_range = False):
    # n_samples: The number of points in a given sample (i.e statistical realisations of one output)
    # check_range: If True, then checks whether predicted masses and radii are [0,1]
    # Returns: An array with the sample
    #X_test = test_data[0]
    #y_test = test_data[1]
    sample = [] # list to append the sample
    model = model_def
    for _ in range(0, n_samples): # produce n_samples realisations at fixed input i0
        testX1 = np.expand_dims(X_test , axis=0) # The input data for the deep network
        result_testX1 = model(testX1)  # Given input data, make prediction for the features: (mass, c_s)
        mass_values = result_testX1[0][1:8] # 7 mass values - the "x-axis"
        cs_values = result_testX1[0][8:15] # 7 sound speed values - the "y-axis"
        data_X1_zip = zip( np.array(mass_values), np.array(cs_values) )  # create pairs (mass, c_s)

        if check_range == True: # check that the predicted (mass, c_s) are within [0,1]
            check_mass = any(element > 1. or element < 0.  for element in mass_values) # tests if 0 < mass < 1
            check_cs   = any(element > 1. or element < 0. for element in cs_values) # tests if 0 < cs < 1
            if check_mass == False and check_cs == False:
                sample.append(list(data_X1_zip)) # Append the given realisation of predicted (mass, c_s) to the list
        else:
            sample.append(list(data_X1_zip))

    sample = np.array(sample)  # Produce array of the sample list
    return sample

##########################
# This function evaluates the results of the deep network for the sound speed prediction according to the statistical pipeline.
def produce_evaluation(test_data, input_list, model, n_samples = 100, α = 2, check_range = True):
      # input_list: list of integers denoting the input data to consider for evaluation
      # n_samples: number of samples for each datapoint
      # α: the sigma level to consider as accepted range for predicted data
      # Returns: A list with the percentage of "accepted" predictions, i.e predicted points which lie in the allowed interval.
    eval_data_x_cs = [] # list to append succesful evaluation of the mass and cs predicion (success = 1)
    X_test = test_data[0]
    y_test = test_data[1]
    for i in input_list:
        sample = produce_sample_cs(X_test[i], model, n_samples = n_samples, check_range = check_range)
        sample = np.array(sample)
        col_i = i
        real_Lambda, real_mass, real_cs = y_test[i][0], y_test[i][1:8], y_test[i][8:15]
        data_temp_x = []
        data_temp_cs = []
        data_temp_x_cs = []
        #mean_Lambda, std_Lambda = np.mean(sample[:,0]), np.std(sample[:,0])
        for j in range(0,len(real_mass)):
            mean_x, std_x = np.mean(sample[:,j][:,0]), np.std(sample[:,j][:,0])
            mean_cs, std_cs  = np.mean(sample[:,j][:,1]), np.std(sample[:,j][:,1])
            if mean_x - α*std_x < real_mass[j] < mean_x + α*std_x and mean_cs - α*std_cs < real_cs[j] < mean_cs + α*std_cs:
                data_temp_x_cs.append(1)
        eval_data_x_cs.append([len(data_temp_x_cs), len(sample)])
    return eval_data_x_cs

##########################
# The definition of the deep model
def produce_model(train_data, units, activation, prior, posterior, activation_last_layer=False):

    if activation_last_layer == True:
        final_activation = 'sigmoid'
    else:
        final_activation = None

    n_features = train_data[0].shape[1]
    norm = train_data[0].shape[0]

    model = tf_keras.Sequential([

    tfpl.DenseVariational(input_shape=(n_features,), units=units,
                              make_prior_fn = get_prior,
                              make_posterior_fn=get_posterior,
                              kl_weight=1/norm,
                              kl_use_exact=False,
                              activation=activation),

    tfpl.DenseVariational(input_shape=(n_features,), units=units,
                              make_prior_fn = get_prior,
                              make_posterior_fn=get_posterior,
                              kl_weight=1/norm,
                              kl_use_exact=False,
                              activation=activation),

    tfpl.DenseVariational(input_shape=(n_features,), units=units,
                              make_prior_fn = get_prior,
                              make_posterior_fn=get_posterior,
                              kl_weight=1/norm,
                              kl_use_exact=False,
                              activation=activation),

    tfpl.DenseVariational(input_shape=(n_features,), units=units,
                              make_prior_fn = get_prior,
                              make_posterior_fn=get_posterior,
                              kl_weight=1/norm,
                              kl_use_exact=False,
                              activation=activation),

    # Output layer with activation function.
    tfpl.DenseVariational(units=15,
                              make_prior_fn = get_prior,
                              make_posterior_fn=get_posterior,
                              kl_weight=1/norm,
                              kl_use_exact=False,
                              activation = final_activation)

                   ])
    return model

##########################
# Custom callback
def training_stop(terminate_at_accuracy = 0.75):

    class CustomCallback(tf_keras.callbacks.Callback):
        def on_epoch_end(self, epoch, logs=None):
            if logs.get('accuracy') >= terminate_at_accuracy:
                self.model.stop_training = True
    callback = CustomCallback()
    return callback

##########################
# Initiates the training of the model
def train_model(model, train_X, train_y, epochs, callbacks = None):

    history = model.fit(train_X, train_y, epochs, verbose=1, callbacks=callbacks)

    return history